# Generated by Django 3.1.5 on 2021-01-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventPoster',
            field=models.CharField(default='C:/Users/Gopi/OneDrive/Documents/Projects/EventManagement/static/images/DefaultEventPoster.jpg', max_length=255),
        ),
    ]
