# Generated by Django 3.1.5 on 2021-01-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_auto_20210123_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('ContactNo', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=255)),
                ('EventName', models.CharField(max_length=50)),
                ('RegType', models.CharField(max_length=15)),
                ('NoOfPeople', models.IntegerField()),
            ],
        ),
    ]
