# Generated by Django 3.1.5 on 2021-01-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
